name: vendas_dw
version: 1.0.0
config-version: 2

profile: vendas_dw
model-paths: ["models"]

models:
  vendas_dw:            # 👈 1º nível = nome do projeto (obrigatório)
    silver:             # 👈 pasta models/silver
      +schema: silver
      +materialized: table

    gold:               # 👈 pasta models/gold
      +schema: gold
      +materialized: table
