version: 2

sources:
  - name: bronze
    database: general_rtxt
    schema: bronze
    tables:
      - name: vendas
      - name: devolucoes
      - name: produtos
      - name: lojas
      - name: vendedores
